#!/usr/bin/env python3
"""Read-only mapping preview: legacy `carte_grises` (vehicule.sql) -> `vehicles` schema.

Does NOT touch any database and does NOT modify vehicule.sql. It parses the
legacy dump (reusing read_vehicule_sql.py's parser), maps each row's columns
onto the CURRENT `Vehicle` model's column names (app/models.py), and writes
the result to a new CSV file for review. Fields with no reliable legacy
source are left blank.

Mapping used (legacy -> vehicles):
    Num_Matricule       -> license_plate
    Nom                 -> owner_name
    Adresse             -> owner_address
    Commune             -> owner_island   (Ngazidja/Nzwani/Mwali -> Grande Comore/Anjouan/Moheli)
    Genre               -> vehicle_type   (normalisé vers les codes de l'app : voiture/pickup/moto/
                                            camion/minibus/bus/ambulance/suv/other ; les 'voiture'
                                            sont affinés en suv/pickup/minibus via Marque+Sous_Marque)
    Marque              -> make           (marque seule, ex. 'RENAULT  KANGOO' -> 'RENAULT')
    Sous_Marque         -> model
    Nbre_CVX            -> nombre_chevaux
    Num_serie           -> vin
    Source_Energie      -> fuel_type      (Essance -> Essence, GasOil -> Gazoil)
    Date_delivrance     -> registration_date
    Per_Annee_MC        -> year           (date de première mise en circulation ; on n'en garde
                                            que l'année, avec correction des années à 5-6 chiffres
                                            causées par un chiffre parasite saisi en trop ; les
                                            années hors 1950-2026, ou non résolvables, sont laissées
                                            vides plutôt que de deviner)
    Observation         -> notes
    Nom_Agent           -> created_by

Extra columns (not on `Vehicle` itself, but on the linked `CarteGrise` model
— appended after the vehicles columns so they aren't lost):
    Nombre_Place        -> places_assises
    Poids_TAC           -> poids_total_autorise
    Poids_vide          -> poids_a_vide
    Charge_Utile        -> charge_utile_ptc
    Profession          -> profession_proprietaire

Everything else in the `vehicles` schema (status, fiscal_class, cv_class,
insurance_*, vignette_*, qr_code_*, track_token, id, ...) has no legacy
equivalent and is left empty in the output CSV.

Usage:
    python3 map_vehicule_to_vehicles.py [path/to/vehicule.sql] [-o out.csv]
"""
import argparse
import csv
import re
import sys
from pathlib import Path

from read_vehicule_sql import (
    parse_create_tables,
    iter_insert_statements,
    split_top_level_tuples,
    split_fields,
    unquote,
)

SOURCE_TABLE = "carte_grises"

NONE_MARKERS = {"NEANT", "NÉANT"}


def clean(value):
    """Strip a legacy field, collapse internal runs of whitespace to a single
    space (some rows are padded to a fixed width, e.g. 255 chars, with
    trailing/internal spaces), and treat the 'NEANT' placeholder (used across
    many columns in vehicule.sql — Profession, Poids_TAC/vide, Charge_Utile,
    Sous_Marque, Marque, Commune — to mean "no value") as blank."""
    v = re.sub(r"\s+", " ", (value or "").strip())
    return "" if v.upper() in NONE_MARKERS else v


def dedupe_repeated_name(value):
    """Some legacy Nom values are the same name typed twice into a padded
    fixed-width field (e.g. 'DJAMAL ISSIMAIL ISSIHAKA' + spaces + itself
    again, 242 chars total) — long enough to overflow the 100-char
    owner_name column on import. If the whole value is two identical halves,
    collapse to one."""
    parts = value.split(" ")
    n = len(parts)
    if n >= 2 and n % 2 == 0:
        half = n // 2
        if parts[:half] == parts[half:]:
            return " ".join(parts[:half])
    return value

# Column order mirrors app/models.py's Vehicle model (minus `id`, which is
# auto-generated by the database and has no legacy equivalent).
VEHICLE_COLUMNS = [
    "license_plate", "owner_name", "owner_phone", "owner_island",
    "vehicle_type", "fuel_type", "usage_type", "color", "status",
    "make", "model", "year", "vin", "owner_address",
    "registration_expiry", "track_token", "registration_date",
    "last_inspection_date", "insurance_company", "insurance_expiry",
    "vignette_expiry", "vignette_payment_approved", "vignette_payment_approved_at",
    "vignette_payment_approved_by", "vignette_payment_method",
    "vignette_payment_requested_at", "vignette_payment_requested_by",
    "vignette_payment_requested_expiry", "vignette_last_paid_at",
    "vignette_last_paid_by", "vignette_last_paid_vignette_amount",
    "vignette_last_paid_penalty_amount", "vignette_last_paid_fines_amount",
    "vignette_last_paid_qr_amount", "vignette_last_paid_total_amount",
    "qr_code_generated_at", "qr_code_expiry", "qr_pending_approval",
    "fiscal_class", "cv_class", "nombre_chevaux", "work_zone", "notes",
    "created_by", "qr_renewed_by", "created_at", "updated_at",
]

# Not part of the Vehicle model — these belong to the linked CarteGrise
# record. Appended after VEHICLE_COLUMNS so they're kept for a future
# CarteGrise-populating import rather than dropped.
CARTE_GRISE_COLUMNS = [
    "places_assises", "poids_total_autorise", "poids_a_vide", "charge_utile_ptc",
    "profession_proprietaire",
]

ISLAND_MAP = {
    "ngazidja": "Grande Comore",
    "grande comore": "Grande Comore",
    "nzwani": "Anjouan",
    "ndzuani": "Anjouan",
    "anjouan": "Anjouan",
    "mwali": "Moheli",
    "moheli": "Moheli",
    "mohéli": "Moheli",
}

MULTI_WORD_MAKES = {
    ("LAND", "ROVER"): "LAND ROVER",
    ("LANDROVER",): "LAND ROVER",
    ("ALFA", "ROMEO"): "ALFA ROMEO",
    ("ALFAROMEO",): "ALFA ROMEO",
    ("MERCEDES", "BENZ"): "MERCEDES BENZ",
}


def extract_make(marque):
    """Pull just the manufacturer name out of `Marque`, which mixes make+model
    (e.g. 'RENAULT  KANGOO' -> 'RENAULT', 'MERCEDES  BENZ  CLASSE' -> 'MERCEDES BENZ')."""
    marque = clean(marque)
    if not marque:
        return ""
    tokens = marque.upper().split()
    if not tokens:
        return ""
    if len(tokens) >= 2 and (tokens[0], tokens[1]) in MULTI_WORD_MAKES:
        return MULTI_WORD_MAKES[(tokens[0], tokens[1])]
    if (tokens[0],) in MULTI_WORD_MAKES:
        return MULTI_WORD_MAKES[(tokens[0],)]
    if tokens[0] == "MERCEDES":
        return "MERCEDES BENZ"
    return tokens[0]


# Genre (legacy free text) -> canonical app vehicle_type code. Checked in order;
# first match wins. Based on the 52 distinct Genre values actually found in
# vehicule.sql (moto/camion/bus/ambulance are already explicit there).
GENRE_KEYWORDS = [
    ("MOTO", "moto"),
    ("AMBULANCE", "ambulance"),
    ("MINI-BUS", "minibus"), ("MINI BUS", "minibus"), ("MINIBUS", "minibus"),
    ("BUS", "bus"),
    ("PICK", "pickup"),
    ("4X4", "suv"),
    ("JEEP", "suv"),
    ("CAMION", "camion"), ("CTTE", "camion"), ("PELLE", "camion"),
    ("COMPACTEUR", "camion"), ("CHARGEUR", "camion"), ("MIXER", "camion"),
    ("NIVELEUS", "camion"), ("BENNE", "camion"), ("TRACTEUR", "camion"),
    ("CITERNE", "camion"), ("HINO", "camion"), ("TRR", "camion"), ("CAM", "camion"),
]

# Within the big "voiture" bucket, refine to a more specific body type using
# the model name (Marque + Sous_Marque). Curated from the models actually
# present in vehicule.sql, plus common regional models likely to appear
# (Toyota/Nissan/Mitsubishi/4x4 brands are common in Comoros).
PICKUP_MODEL_KEYWORDS = [
    "HILUX", "HI LUX", "L200", "RANGER", "D-MAX", "DMAX", "TRITON", "NAVARA", "AMAROK",
]
SUV_MODEL_KEYWORDS = [
    "SPORTAGE", "TUCSON", "RAV4", "RAV 4", "QASHQAI", "SANTAFE", "SANTA FE", "SORENTO",
    "FORTUNER", "DUSTER", "2008", "3008", "5008", "X-TRAIL", "XTRAIL", "CR-V", "CRV",
    "VITARA", "TERRIOS", "PAJERO", "MONTERO", "PRADO", "LAND CRUISER", "LANDCRUISER",
    "TROOPER", "RODEO", "KORANDO", "REXTON", "ACTYON", "TIVOLI", "CAPTUR", "KADJAR",
    "KOLEOS", "OUTLANDER", "ASX", "JUKE", "KUGA", "ESCAPE", "CHEROKEE", "WRANGLER",
    "COMPASS", "PATRIOT", "RENEGADE", "CAYENNE", "TOUAREG", "XC60", "XC90",
    "EVOQUE", "DISCOVERY", "DEFENDER", "FREELANDER",
]
MINIBUS_MODEL_KEYWORDS = [
    "HIACE", "ZAFIRA", "ESPACE", "TOURAN", "C8", "807",
]
# Brands that are (almost) exclusively SUVs, used as a fallback when the
# model itself didn't match a keyword above.
SUV_ONLY_MAKES = {"LAND ROVER", "JEEP", "SSANGYONG"}


def classify_genre(genre):
    g = (genre or "").strip().upper()
    for kw, cat in GENRE_KEYWORDS:
        if kw in g:
            return cat
    # Everything else (VOITURE/V P/VP/VITURE/VOTURE typos, blank, or unknown
    # abbreviations like TCP/MTT2/TEM/VV) defaults to the generic car bucket,
    # which is then refined below using the make/model.
    return "voiture"


def classify_vehicle_type(genre, marque_raw, sous_marque):
    base = classify_genre(genre)
    if base != "voiture":
        return base
    combined = f"{clean(marque_raw)} {clean(sous_marque)}".upper()
    for kw in PICKUP_MODEL_KEYWORDS:
        if kw in combined:
            return "pickup"
    for kw in SUV_MODEL_KEYWORDS:
        if kw in combined:
            return "suv"
    for kw in MINIBUS_MODEL_KEYWORDS:
        if kw in combined:
            return "minibus"
    if extract_make(marque_raw) in SUV_ONLY_MAKES:
        return "suv"
    return "voiture"


FUEL_MAP = {
    "essance": "Essence",
    "essence": "Essence",
    "gasoil": "Gazoil",
    "gas oil": "Gazoil",
    "gazoil": "Gazoil",
    "electrique": "Electrique",
    "electric": "Electrique",
}


def map_island(commune):
    commune = clean(commune)
    if not commune:
        return ""
    key = commune.lower()
    return ISLAND_MAP.get(key, commune)


def map_fuel(source_energie):
    source_energie = clean(source_energie)
    if not source_energie:
        return ""
    key = source_energie.lower()
    return FUEL_MAP.get(key, source_energie)


def map_date(raw):
    """Legacy dates come as ' 30/10/2021' or '2008-11-17'. Normalize to YYYY-MM-DD, else keep raw."""
    if not raw:
        return ""
    raw = raw.strip()
    m = re.match(r"^(\d{2})/(\d{2})/(\d{4})$", raw)
    if m:
        d, mo, y = m.groups()
        return f"{y}-{mo}-{d}"
    if re.match(r"^\d{4}-\d{2}-\d{2}$", raw):
        return raw
    return raw


MIN_PLAUSIBLE_YEAR = 1950
MAX_PLAUSIBLE_YEAR = 2026


def extract_year(raw_date):
    """Pull just the year out of Per_Annee_MC (date de première mise en
    circulation). Some rows have a stray extra digit (typo) making the year
    5 or 6 digits, e.g. '22010-10-26' instead of '2010-10-26'. Try removing
    each possible single extra digit and keep the result only if exactly
    one position yields a plausible year — when several positions are
    plausible (e.g. '20012' could read as 2001, 2002 or 2012), it's
    genuinely ambiguous from the digits alone, so this returns blank rather
    than guessing (see MANUAL_YEAR_OVERRIDES for those, checked by hand).
    Anything outside 1950-2026 (placeholders like '0001-01-01', impossible
    dates like '1883-03-03') is also left blank."""
    if not raw_date:
        return ""
    m = re.match(r"^(\d+)-\d{2}-\d{2}$", raw_date.strip())
    if not m:
        return ""
    yr = m.group(1)

    def plausible(y):
        return len(y) == 4 and MIN_PLAUSIBLE_YEAR <= int(y) <= MAX_PLAUSIBLE_YEAR

    if len(yr) == 4:
        return yr if plausible(yr) else ""

    excess = len(yr) - 4
    if excess <= 0:
        return ""
    if excess == 1:
        candidates = {yr[:i] + yr[i + 1:] for i in range(len(yr))}
    else:
        candidates = {yr[excess:], yr[:-excess]}
    plausible_candidates = {c for c in candidates if plausible(c)}
    if len(plausible_candidates) == 1:
        return next(iter(plausible_candidates))
    return ""


# Per_Annee_MC entries where the extra stray digit sits in the MIDDLE of the
# string (right after the century, e.g. '20202' = '20' + extra '2' + '02')
# rather than at an edge — dropping from the front/back alone is ambiguous
# there (e.g. '20012' could plausibly be 2001, 2002 or 2012). Confirmed by
# hand, plate by plate, against the real records; the pattern that emerged
# is "century (first 2 digits) + last 2 digits, drop what's in between" —
# 122BQ73 and 669BT73 weren't explicitly checked but follow the identical
# '200XY' shape as every confirmed case, so they're inferred by that same
# rule rather than left blank.
MANUAL_YEAR_OVERRIDES = {
    "899BM73": "2002",  # raw 20202
    "558BN73": "1998",  # raw 19998
    "961BN73": "2012",  # raw 20012
    "478BP73": "2003",  # raw 20003
    "645BP73": "2001",  # raw 20001
    "875BP73": "2005",  # raw 20005
    "122BQ73": "2008",  # raw 20008 (inferred, not individually confirmed)
    "939BA73": "2001",  # raw 20001
    "119BR73": "2006",  # raw 20006
    "286BR73": "2001",  # raw 20001
    "388BR73": "2003",  # raw 20003
    "190BS73": "2019",  # raw 20219
    "474BS73": "2021",  # raw 20221
    "634BS73": "2021",  # raw 20221
    "669BT73": "2004",  # raw 20004 (inferred, not individually confirmed)
    "892BU73": "2018",  # raw 20018
    "559BV73": "2001",  # raw 20001

    # Second batch: Per_Annee_MC already had 4 digits but an implausible
    # value (placeholder like '0001-01-01', or impossible like '1883-03-03').
    # Confirmed by hand for most; a few (marked "inferred") follow the exact
    # same '20' + last-2-digits pattern as every confirmed case in this
    # batch, so they're filled in by analogy rather than left blank.
    "814BM73": "2001",  # raw 0001 (confirmed)
    "868BM73": "2004",  # raw 0004 (confirmed)
    "958BM73": "2001",  # raw 0001 (confirmed)
    "077BN73": "2004",  # raw 0004 (confirmed)
    "173BN73": "1993",  # raw 1883 (confirmed — not a digit-pattern fix)
    "269BN73": "2002",  # raw 0002 (inferred)
    "302BN73": "2003",  # raw 0003 (inferred)
    "340BN73": "2005",  # raw 2205 (confirmed)
    "438BN73": "2020",  # raw 0020 (confirmed)
    "466BN73": "2019",  # raw 0019 (confirmed)
    "530BN73": "2005",  # raw 0005 (inferred)
    "602BN73": "2014",  # raw 0214 (confirmed)
    "868BN73": "2007",  # raw 0007 (inferred)
    "087BP73": "2020",  # raw 0020 (confirmed)
    "603BP73": "2017",  # raw 0017 (inferred)
    "233BQ73": "2022",  # raw 0022 (inferred)
    "048BR73": "2011",  # raw 0211 (confirmed)
    "417BR73": "2014",  # raw 1014 (confirmed)
    "714BR73": "2012",  # raw 5012 (confirmed)
    "503BS73": "2004",  # raw 0004 (confirmed)
    "975BS73": "2018",  # raw 2028 (confirmed — not a digit-pattern fix)
    "032BT73": "2001",  # raw 0001 (confirmed)
    "151BT73": "2018",  # raw 2088 (confirmed — not a digit-pattern fix)
    "298BT73": "2005",  # raw 0005 (inferred)
    "317BT73": "2009",  # raw 0009 (inferred)
    "456BT73": "2018",  # raw 0218 (inferred)
    "380BU73": "2015",  # raw 1015 (confirmed)
    "580BV73": "2007",  # raw 0207 (confirmed)
    "669BV73": "2007",  # raw 0207 (confirmed)
    "692BV73": "2012",  # raw 1012 (inferred)
    "711BV73": "2016",  # raw 0016 (inferred)
    "153BX73": "2023",  # raw 0023 (inferred)
    "281BX73": "2013",  # raw 0213 (confirmed as "2-13" -> read as 2013)
}


def map_row(legacy):
    row = {col: "" for col in VEHICLE_COLUMNS + CARTE_GRISE_COLUMNS}
    # [:N] truncations mirror the Vehicle/CarteGrise column limits in
    # app/models.py — a safety net so a corrupted legacy value (e.g. a name
    # padded/duplicated into a 255-char field) can never overflow a Postgres
    # varchar column and crash the whole import, even if some future row
    # slips past the cleaning above.
    row["license_plate"] = (legacy.get("Num_Matricule") or "").strip()[:20]
    row["owner_name"] = dedupe_repeated_name(clean(legacy.get("Nom")))[:100]
    row["owner_address"] = clean(legacy.get("Adresse"))[:255]
    row["owner_island"] = map_island(legacy.get("Commune"))[:50]
    row["vehicle_type"] = classify_vehicle_type(
        legacy.get("Genre"), legacy.get("Marque"), legacy.get("Sous_Marque")
    )
    row["make"] = extract_make(legacy.get("Marque"))[:50]
    row["model"] = clean(legacy.get("Sous_Marque"))[:50]
    row["nombre_chevaux"] = clean(legacy.get("Nbre_CVX"))
    row["vin"] = clean(legacy.get("Num_serie"))[:50]
    row["fuel_type"] = map_fuel(legacy.get("Source_Energie"))[:50]
    row["registration_date"] = map_date(legacy.get("Date_delivrance"))
    plate = (legacy.get("Num_Matricule") or "").strip()
    row["year"] = MANUAL_YEAR_OVERRIDES.get(plate) or extract_year(legacy.get("Per_Annee_MC"))
    row["notes"] = clean(legacy.get("Observation"))
    row["created_by"] = clean(legacy.get("Nom_Agent"))[:80]
    row["places_assises"] = clean(legacy.get("Nombre_Place"))[:20]
    row["poids_total_autorise"] = clean(legacy.get("Poids_TAC"))[:50]
    row["poids_a_vide"] = clean(legacy.get("Poids_vide"))[:50]
    row["charge_utile_ptc"] = clean(legacy.get("Charge_Utile"))[:50]
    row["profession_proprietaire"] = clean(legacy.get("Profession"))[:150]
    return row


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", nargs="?", default="vehicule.sql", help="Path to the .sql dump")
    parser.add_argument("-o", "--output", default="vehicules_mappes.csv", help="Fichier CSV de sortie")
    args = parser.parse_args()

    path = Path(args.path)
    if not path.exists():
        print(f"Fichier introuvable : {path}", file=sys.stderr)
        sys.exit(1)

    sql_text = path.read_text(encoding="utf-8", errors="replace")
    tables = parse_create_tables(sql_text)

    if SOURCE_TABLE not in tables:
        print(f"Table `{SOURCE_TABLE}` introuvable dans {path}", file=sys.stderr)
        sys.exit(1)

    cols = tables[SOURCE_TABLE]
    mapped_rows = []
    for table, values_blob in iter_insert_statements(sql_text):
        if table != SOURCE_TABLE:
            continue
        for tuple_body in split_top_level_tuples(values_blob):
            fields = [unquote(f) for f in split_fields(tuple_body)]
            legacy = dict(zip(cols, fields))
            mapped_rows.append(map_row(legacy))

    out_path = Path(args.output)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=VEHICLE_COLUMNS + CARTE_GRISE_COLUMNS)
        writer.writeheader()
        writer.writerows(mapped_rows)

    print(f"{len(mapped_rows)} lignes mappées depuis `{SOURCE_TABLE}`.")
    print(f"Fichier écrit : {out_path.resolve()}")
    print("Aucune donnée n'a été écrite en base — c'est un fichier de relecture uniquement.")

    from collections import Counter
    type_counts = Counter(r["vehicle_type"] for r in mapped_rows)
    print("\nRépartition vehicle_type :")
    for cat, n in type_counts.most_common():
        print(f"  {cat:10s} {n}")

    year_resolved = sum(1 for r in mapped_rows if r["year"])
    print(f"\nAnnée (year) extraite pour {year_resolved}/{len(mapped_rows)} lignes "
          f"({len(mapped_rows) - year_resolved} laissées vides, valeur non fiable).")


if __name__ == "__main__":
    main()
